// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXpPbaSlP1d-MktIW5YVljK9gptgpjJns',
    appId: '1:915467532005:web:a473fb9df0d296ee27c60c',
    messagingSenderId: '915467532005',
    projectId: 'flutterpractical-9fc40',
    authDomain: 'flutterpractical-9fc40.firebaseapp.com',
    storageBucket: 'flutterpractical-9fc40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOWyX81doRfbg9djrH2EHH2XwOF612BU',
    appId: '1:915467532005:android:89e8ece26c23e4b027c60c',
    messagingSenderId: '915467532005',
    projectId: 'flutterpractical-9fc40',
    storageBucket: 'flutterpractical-9fc40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBytL_9OQwCqR9V6b9aa0xvCF_TmbFPgvk',
    appId: '1:915467532005:ios:4bb10f61e45a11cf27c60c',
    messagingSenderId: '915467532005',
    projectId: 'flutterpractical-9fc40',
    storageBucket: 'flutterpractical-9fc40.appspot.com',
    iosClientId: '915467532005-facaavn7k7qrimj35gq31vi67n5fj3u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPractical',
  );
}
